name: C/C++ CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run cmake
      run: cmake .
    - name: run make
      run: make
    - name: make distcheck
      run: make distcheck
    - name: copy to /usr/bin
      run: cp ./stress /usr/bin/stress
    - name: set exec permission
      run: chmod +x /usr/bin/stress
    - name: run tests
      run: cd tests & python3 tests.py
