name: CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: run cmake
      run: export CC=/usr/bin/clang && export CXX=/usr/bin/clang++ && cmake . && cmake --build . -j 6
    - name: copy to /usr/bin
      run: sudo cp ./stress /usr/bin/stress
    - name: set exec permission
      run: sudo chmod +x /usr/bin/stress
    - name: run tests
      run: cd tests && python3 start.py